apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
    app: {{app}}
spec:
  image: {{image}}
  port: 8080
  strategy:
    rollingUpdate: # Bruk kun Recreate når vi deployer store/ukompatible migreringer
      maxSurge: 100%
      maxUnavailable: 99%
  liveness:
    path: /isalive
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isready
    timeout: 1
  prometheus:
    enabled: true
  secureLogs:
    enabled: true
  replicas:
    min: 4
    max: 4
    cpuThresholdPercentage: 75
  kafka:
    pool: { { kafka_pool } }
  resources:
    limits:
      cpu: "2024m"
      memory: "512Mi"
    requests:
      cpu: "1024m"
      memory: "512Mi"
  {{#if ingresses}}
     ingresses:
       {{#each ingresses}}
          - {{this}}
        {{/each}
  {{/if}}
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-soknadsdialog
        - application: dp-behov-soknad-pdf
        - application: dp-behov-journalforing
        - application: dp-soknad-veileder
        - application: dp-innsyn
        - application: dp-dagpenger
        {{#if wonderwalled}}
            - application: tokens-token-generator
                namespace: aura
        {{/if}}
    outbound:
      rules:
        - application: dp-innsyn
        - application: sokos-kontoregister-person
          namespace: okonomi
      external:
        - host: { { PDL_API_HOST } }
  env:
    - name: PERSON_KONTO_REGISTER_SCOPE
      value: {{PERSON_KONTO_REGISTER_SCOPE}}
    - name: PDL_API_HOST
      value: {{PDL_API_HOST}}
    - name: PDL_AUDIENCE
      value: {{PDL_AUDIENCE}}
    - name: DP_INNSYN_AUDIENCE
      value: {{DP_INNSYN_AUDIENCE}}
    - name: DP_INNSYN_URL
      value: http://dp-innsyn
    - name: JAVA_OPTS
      value: -XX:ActiveProcessorCount=2
    #  value: -XX:+UseG1GC -XX:MaxRAMPercentage=75.0 -XX:ActiveProcessorCount=2
  gcp:
    sqlInstances:
      - name: dp-soknad-v1
        type: POSTGRES_14
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: true
        pointInTimeRecovery: true
        retainedBackups: { { point_in_time_recovery_days } }
        diskSize: {{db_size}}
        diskAutoresize: true
        autoBackupHour: 3
        maintenance:
          day: 1
          hour: 3
        databases:
          - name: dp-soknad
            envVarPrefix: DB
        cascadingDelete: false
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudprofiler.agent
