apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
    app: {{app}}
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isready
    timeout: 1
  prometheus:
    enabled: true
  secureLogs:
    enabled: true
  replicas:
    min: 4
    max: 4
    cpuThresholdPercentage: 75
  kafka:
     pool: {{ kafka_pool }}
  resources:
    limits:
      cpu: "1024m"
      memory: "512Mi"
    requests:
      cpu: "512m"
      memory: "512Mi"
  {{ ingresses }}
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-soknadsdialog
        - application: dp-behov-soknad-pdf
        - application: dp-behov-journalforing
    outbound:
      rules:
        - application: dp-innsyn
  env:
    - name: DP_PROXY_SCOPE
      value: {{dp_proxy_scope}}
    - name: DP_PROXY_URL
      value: {{dp_proxy_url}}
    - name: PDL_API_URL
      value: {{PDL_API_URL}}
    - name: PDL_AUDIENCE
      value: {{PDL_AUDIENCE}}
    - name: DP_INNSYN_AUDIENCE
      value: {{DP_INNSYN_AUDIENCE}}
    - name: DP_INNSYN_URL
      value: http://dp-innsyn
    - name: JAVA_OPTS
      value: -XX:+UseG1GC -XX:MaxRAMPercentage=75.0 -XX:ActiveProcessorCount=2
  gcp:
    sqlInstances:
      - name: dp-soknad-v1
        type: POSTGRES_14
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: true
        pointInTimeRecovery: true
        retainedBackups: {{ point_in_time_recovery_days }}
        diskSize: {{db_size}}
        diskAutoresize: true
        autoBackupHour: 3
        maintenance:
          day: 1
          hour: 3
        databases:
          - name: dp-soknad
            envVarPrefix: DB
        cascadingDelete: false
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudprofiler.agent