@startuml
title 
Søknadsflyt – flyt for Søker oppretter søknad og ferdigstiller den
end title           
[*]-->UnderOpprettelse 
UnderOpprettelse --> Påbegynt
Påbegynt --> Ferdigstill
Ferdigstill --> AvventerArkiverbarSøknad
AvventerArkiverbarSøknad --> AvventerMidlertidligJournalføring
AvventerMidlertidligJournalføring --> AvventerJournalføring
AvventerJournalføring --> Journalført
Journalført--> [*]
@enduml