@startuml
title 
Søknadsflyt – flyt for Søker oppretter søknad og ferdigstiller den
end title           
[*]-->UnderOpprettelse 
UnderOpprettelse --> Påbegynt
Påbegynt --> Innsendt
Innsendt--> [*]
@enduml