@startuml
title 
Søknadsflyt – flyt for Søker oppretter søknad og ferdigstiller den
end title           
[*]-->UnderOpprettelse 
UnderOpprettelse --> Påbegynt
Påbegynt --> AvventerArkiverbarSøknad
AvventerArkiverbarSøknad --> AvventerMidlertidligJournalføring
AvventerMidlertidligJournalføring --> AvventerJournalføring
AvventerJournalføring--> [*]
@enduml