apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
    app: {{app}}
spec:
  image: {{image}}
  port: 8080
  strategy:
    rollingUpdate: # Bruk kun Recreate når vi deployer store/ukompatible migreringer
      maxSurge: 100%
      maxUnavailable: 99%
  liveness:
    path: /isalive
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isready
    timeout: 1
  prometheus:
    enabled: true
  secureLogs:
    enabled: true
  replicas:
    min: 4
    max: 4
  kafka:
    pool: {{ kafka_pool }}
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  {{#if ingresses}}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  {{/if}}
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-soknadsdialog
        - application: dp-behov-soknad-pdf
        - application: dp-behov-journalforing
        - application: dp-innsyn
        - application: dp-dagpenger
        {{#if wonderwalled}}
        - application: tokenx-token-generator
          namespace: aura
        {{/if}}
    outbound:
      rules:
        - application: dp-innsyn
        - application: sokos-kontoregister-person
          namespace: okonomi
      external:
        - host: {{ PDL_API_HOST }}
        - host: aareg-services-q2.dev-fss-pub.nais.io
        - host: ereg-services-q2.dev-fss-pub.nais.io

  env:
    - name: PERSON_KONTO_REGISTER_SCOPE
      value: {{PERSON_KONTO_REGISTER_SCOPE}}
    - name: PDL_API_HOST
      value: {{PDL_API_HOST}}
    - name: PDL_AUDIENCE
      value: {{PDL_AUDIENCE}}
    - name: DP_INNSYN_AUDIENCE
      value: {{DP_INNSYN_AUDIENCE}}
    - name: DP_INNSYN_URL
      value: http://dp-innsyn
    - name: AAREG_API_HOST
      value: {{AAREG_API_HOST}}
    - name: AAREG_AUDIENCE
      value: {{AAREG_AUDIENCE}}
    - name: EREG_API_HOST
      value: {{EREG_API_HOST}}
    - name: JAVA_OPTS
      value: -XX:ActiveProcessorCount=2
  gcp:
    sqlInstances:
      - name: dp-soknad-v1
        type: POSTGRES_14
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: true
        pointInTimeRecovery: true
        retainedBackups: {{ point_in_time_recovery_days }}
        diskSize: {{db_size}}
        diskAutoresize: true
        autoBackupHour: 3
        maintenance:
          day: 1
          hour: 3
        databases:
          - name: dp-soknad
            envVarPrefix: DB
        cascadingDelete: false
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudprofiler.agent
