apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
    app: {{app}}
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isready
    timeout: 1
  prometheus:
    enabled: true
  secureLogs:
    enabled: true
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 75
  kafka:
     pool: {{ kafka_pool }}
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  {{ ingresses }}
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-soknadsdialog
  env:
    - name: DP_PROXY_SCOPE
      value: {{dp_proxy_scope}}
    - name: DP_PROXY_URL
      value: {{dp_proxy_url}}
    - name: PDL_API_URL
      value: {{PDL_API_URL}}
    - name: PDL_AUDIENCE
      value: {{PDL_AUDIENCE}}
  gcp:
    sqlInstances:
      - name: dp-soknad-v1
        type: POSTGRES_14
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: false
        diskSize: {{db_size}}
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: soknad
            envVarPrefix: DB
        cascadingDelete: false
