@startuml

package "Søknadsløsningen" {
    component "[[https://github.com/navikt/dp-soknadsdialog Soknadsdialog]]" as soknadsdialog
    component "[[https://github.com/navikt/dp-soknad Soknad]]" as soknad
    database db as soknadDb
    component "[[https://github.com/navikt/dp-quiz Quiz]]" as quiz
    database db as quizDb
    component "[[https://github.com/navikt/dp-mellomlagring mellomlager]]" as mellomlager
    database db as mellomlagerDb
    component "[[https://github.com/navikt/dp-behov-soknad-pdf Behov PDF]]" as behovPdf
    component "[[https://github.com/navikt/dp-behov-journalforing Behov journalforing]]" as behovJournalforing
    component "[[https://github.com/navikt/dp-behov-brukernotifikasjon Behov brukernotifikasjon]]" as behovBrukernotifikasjon
}

soknadsdialog --> soknad
soknadsdialog -r-> mellomlager
mellomlager -r-> mellomlagerDb
soknad -r-> soknadDb
soknad --> behovPdf
soknad --> behovJournalforing
soknad --> behovBrukernotifikasjon
soknad --> quiz
quiz --> quizDb
@enduml
