name: Build and deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'alerts/**'
      - '.github/workflows/deploy-staus-no-alert.yaml'
      - '.github/workflows/reviewdog.yaml'

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v3
        with:
          arguments: build installDist --configuration-cache

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        if: ${{ github.actor != 'dependabot[bot]' }}
        id: docker-build-push
        with:
          team: teamdagpenger
          dockerfile: mediator/Dockerfile # optional, default Dockerfile
          docker_context: mediator # optional, default .
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    needs: [ build ]
    if: github.ref == 'refs/heads/feature/ta_imot_søknadId'
    runs-on: ubuntu-latest
    environment: dev-gcp
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: mediator/.nais/nais.yaml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: mediator/.nais/dev/vars.yaml
          PRINT_PAYLOAD: true

  deploy-prod:
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod-gcp
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: mediator/.nais/nais.yaml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: mediator/.nais/prod/vars.yaml
          PRINT_PAYLOAD: true

