name: Vulnerabilities scanning of dependencies
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rm gradle.properties # Workaround to disable configuration-cache
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/gradle-jdk17@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
        args: |
          --org=teamdagpenger \
          --all-sub-projects \
          --configuration-attributes=usage:java-runtime \
          --remote-repo-url=https://github.com/${{ github.repository }}.git